from typing import Protocol, Optional, List
from domain.entities.user_entity import User

class MongoDBRepository(Protocol):
    def upsert_user(self, user: User) -> Optional[User]: ...
    def get_user_by_email(self, email: str) -> Optional[User]: ...
    def list_users(self, role: Optional[str]) -> List[User]: ...
    def assign_role(self, email: str, role: str) -> Optional[User]: ...
    def remove_role(self, email: str) -> Optional[User]: ...